name = "InvariantModels"
uuid = "8e67f854-b91b-4c84-9489-d19c7173165d"
authors = ["Robert Szalai <r.szalai@bristol.ac.uk> and contributors"]
version = "0.0.1"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
