name = "InvariantModels"
uuid = "8e67f854-b91b-4c84-9489-d19c7173165d"
version = "0.0.1"
authors = ["Robert Szalai <r.szalai@bristol.ac.uk> and contributors"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLSO = "9da8a3cd-07a3-59c0-a743-3fdc52c30d11"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ManifoldDiff = "af67fdf4-a580-4b9f-bbec-742ef357defd"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
ManifoldsBase = "3362f125-f0bb-47a3-aa74-596ffd7ef2fb"
Manopt = "0fc0a36d-df90-57f3-8f93-d78a9fc72bb5"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TaylorSeries = "6aa5eb33-94cf-58f4-a9d0-e4b2c4fc25ea"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
Combinatorics = "1.0.3"
ComponentArrays = "0.15.30"
DifferentialEquations = "7.17.0"
ForwardDiff = "1.2.2"
Interpolations = "0.16.2"
JLSO = "2.7.0"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.12.0"
Makie = "0.24.6"
ManifoldDiff = "0.4.5"
Manifolds = "0.11.2"
ManifoldsBase = "2.1.0"
Manopt = "0.5.25"
NLsolve = "4.5.1"
NonlinearSolve = "4.12.0"
Printf = "1.11.0"
Random = "1.11.0"
RecursiveArrayTools = "3.39.0"
StaticArrays = "1.9.15"
StatsBase = "0.34.7"
TaylorSeries = "0.20.9"
Tullio = "0.3.8"
UnicodePlots = "3.8.1"
